### ISSUE TITLE
why is this commented out? how to sign & send a Tx?

### ISSUE THREAD

**Issue by hackphobic** [cavemanloverboy/oxylana#1]
https://github.com/cavemanloverboy/oxylana/blob/0060aec5e48167ac8f97d58bee38ef3ed0b00b1f/frontend/src/phantom.rs#L19

**Comment by cavemanloverboy** [comment]
This mvp uses phantom's `request` method. Check out https://github.com/cavemanloverboy/oxylana/blob/0060aec5e48167ac8f97d58bee38ef3ed0b00b1f/frontend/src/main.rs#L161-L175.

For more information, check out phantom's docs [here](https://docs.phantom.app/getting-started-with-solana/sending-a-transaction). It is theoretically possible to construct a `Transaction` JSObject and then use this commented out `signAndSendTransaction` method. If you want to try to tackle it I will happily take a PR.
